### ISSUE TITLE
Does this still work?

### ISSUE THREAD

**Issue by LustfulAdventurer** [zNiGhTFuRyZNTT/Discord-Avatar-Autochange#1]
I know its old but i would really like something like this, i did everything that was said to do but it seems like it doesnt work, so is this still code still alive?

When i try to test it, i get this message
 [{
	"resource": "/c:/Users/MPC-001/Desktop/Discord-Avatar-Autochange-main/main.pyw",
	"owner": "_generated_diagnostic_collection_name_#0",
	"code": {
		"value": "reportMissingImports",
		"target": {
			"$mid": 1,
			"path": "/microsoft/pyright/blob/main/docs/configuration.md",
			"scheme": "https",
			"authority": "github.com",
			"fragment": "reportMissingImports"
		}
	},
	"severity": 4,
	"message": "Import \"dotenv\" could not be resolved",
	"source": "Pylance",
	"startLineNumber": 1,
	"startColumn": 6,
	"endLineNumber": 1,
	"endColumn": 12
}]

**Comment by ArminAmiriDev** [comment]
Hello,
I will update the code as soon as possible to work as desired.
Thanks for expressing your interest in this project.

Regards,
Armin.

**Comment by LustfulAdventurer** [comment]
Thank you for your swift reply,
I will be looking forward to it.

Cheers

**Comment by ArminAmiriDev** [comment]
Hello, 
The code is updated and working.
Place your discord account token in .env ,
Put at least 2 images in the images directory.
Please follow these steps:
1- install requirements "pip install -r requirements.txt"
2- try running the main.pyw file directly in the terminal "py or python3 main.pyw"
3- if it is working then stop and once again try and run Launcher.exe
4- if Launcher.exe is working, you can stop the process by running the stop.bat

Add to Start up:
To add to start up:
1-create a shortcut of Launcher.exe and paste it in the startup directory:
something like: C:/Users/yourUsername/AppData/Roaming/Microsoft/Windows/Start Menu/Programs/Startup/
2- Make sure to rename the shortcut to Launcher.exe
3- Later on if you ever wanted to remove from start up, you can either remove the shortcut from startup manually or by running the uninstall.exe file and choosing option 2

I hope that helps,
Thanks for using my project, If you liked it please share with your friend.
Should you have any other issues don't hesitate to ask.

Regards
Armin.

**Comment by LustfulAdventurer** [comment]
Hello,

I thank you for your swift work, so ive downloaded the whole code again, set up my token and interval, put in some images which i know can work with Discord, but everytime i try the program, my discord profile pic changes to nothing

![Desktop Screenshot 2023 10 21 - 16 42 03 27](https://github.com/zNiGhTFuRyZNTT/Discord-Avatar-Autochange/assets/146451799/16d2e15b-a279-48eb-bba6-0cfa774aaa1d)

Like this, ive tried multiple images but everyone ends like this.

Thank you for your help.

Cheers.

**Comment by ArminAmiriDev** [comment]
Hello,
I modified and tested the code on Linux and Windows and it worked prefect.
Please use the new code, make sure all dependencies are installed, preferably use a python virtual environment.

Try again and let me know the outcome, if it failed again I’ll arrange a time so that we can meet on Discord and I will help you fix it.

Regards,
Armin.

**Comment by LustfulAdventurer** [comment]
Hello,

Armin i really appreciate your help, i downloaded the whole code again, set up my discord token and interval in seconds (I wanted 10 minutes so i set up 600 seconds), tried the code with py main.pyw and the code started
![Desktop Screenshot 2023 10 21 - 18 16 29 00](https://github.com/zNiGhTFuRyZNTT/Discord-Avatar-Autochange/assets/146451799/99597908-66e6-4a5d-ba55-30177db8466a)
like this, but my profile pic didnt change, everyone just sees a blank pfp like i showed u before, same result followed me using the launcher.exe. Im not really fluent in code so I dont know if im doing something wrong but the only other thing which could be influenced by my idiocy is the token, i dont know any other way of getting my discord token apart from going to the discord web form and using developer tools to get it. By any chance could this be the reason? But if the token is wrong how can it change my profile pic to blank in the first place?
I apologize for my lack of knowledge in coding.

Cheers and thanks Armin.

**Comment by ArminAmiriDev** [comment]
Hello,

No token seems to be working correctly, it’s currently 3:30am in Australian time, please add me on Discord and I we will arrange a time when I can help you fix the issue.

My Username is: znightfuryznt

Regards,
Armin.

**Comment by elliot710** [comment]
I tried but I'm getting `[>] Initializing ...
[>] Started!
All images -> //edited//
{"message": "401: Unauthorized", "code": 0}
Changed to -> '00000-4281973406.jpeg' - number = 0` response. Maybe the request is missing something? I deactivated 2FA but nothing changed.

**Comment by LustfulAdventurer** [comment]
I basically redownloaded the code and started it and it works nicely now, funny thing is that when i stopped it and tried the previous code that didnt work it started working as well, so sorry i cant really help with this.
